routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\ArticleController;
use \App\Http\Controllers\ContactController;
use \App\Http\Controllers\AdminController;

Route::get('/', [ArticleController::class, 'index'])->name('main');

Route::prefix('/articles')->name('articles.')->group(function () {
    Route::get('/create', [ArticleController::class, 'create'])->name('create')->middleware('auth');
    Route::get('/{article}', [ArticleController::class, 'show'])->name('detail');
    Route::get('/{article}/edit', [ArticleController::class, 'edit'])->name('edit');
    Route::post('/', [ArticleController::class, 'store'])->name('store');
    Route::delete('/{article}', [ArticleController::class, 'destroy'])->name('destroy');
    Route::patch('/{article}', [ArticleController::class, 'update'])->name('update');
    Route::get('/tag/{tag}', [ArticleController::class, 'showByTag'])->name('showByTag');
});

Route::get('/contacts', [ContactController::class, 'create'])->name('contacts.form');
Route::post('/contacts', [ContactController::class, 'store'])->name('contacts.store');

Route::get('/admin', [AdminController::class, 'index'])->name('admin');

Route::fallback(function () {
    return redirect()->route('main');
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;
}

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $guarded = [];

    use HasFactory;

    public function articles()
    {
        return $this->belongsToMany(Article::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory;

    protected $guarded = [];
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function index()
    {
        return view('admin.feedback.index', ['contacts' => Contact::latest()->get()]);
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ArticleRequest;
use App\Models\Article;
use App\Models\Tag;
use App\Models\Task;
use App\Services\TagsSynchronizer;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    public function index()
    {
        $articles = Article::with('user')->latest()->get();
        return view('index', ['articles' => $articles]);
    }

    public function show(Article $article)
    {
        return view('articles.detail', ['article' => $article]);
    }

    public function store(ArticleRequest $request, TagsSynchronizer $tagSync)
    {
        $requestData = $request->validated();

        $article = new Article();
        $article->slug = $requestData['slug'];
        $article->name = $requestData['name'];
        $article->previewText = $requestData['previewText'];
        $article->detailText = $requestData['detailText'];
        $article->published = (bool) request('published');
        $article->user_id = request()->user()->id;
        $article->save();

        $tags = collect(explode(', ', $request->get('tags')));

        if ($tags->isNotEmpty()) {
            $tagSync->sync($article, $tags);
        }

        return redirect()->route('main');
    }

    public function create()
    {
        //Форма создания статьи
        return view('articles.create', ['article' => new Article()]);
    }

    public function destroy(Article $article)
    {
        $article->delete();
        return redirect()->route('main');
    }

    public function edit(Article $article)
    {
        return view('articles.edit', ['article' => $article]);
    }

    public function update(Article $article, ArticleRequest $request, TagsSynchronizer $tagSync)
    {
        $requestData = $request->validated();

        $article->update(array_merge($requestData, ['published' => (bool) $request->get('published')]));

        $tags = $article->tags->keyBy('name');
        $requestTags = collect(explode(', ', $request->get('tags')))->keyBy(function ($item) {return $item;});

        $tagsToAttach = $requestTags->diffKeys($tags);
        $tagsToDetach = $tags->diffKeys($requestTags);

        $tagSync->sync($article, $tagsToAttach, $tagsToDetach);

        return redirect()->route('main');
    }

    public function showByTag(Tag $tag)
    {
        return view('index', ['articles' => $tag->articles()->latest()->get()]);
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function create()
    {
        return view('contacts.index');
    }

    public function store(Request $request)
    {
        $requestData = $request->validate([
            'email' => ['required'],
            'message' => ['required'],
        ]);

        $contact = new Contact();
        $contact->email = $requestData['email'];
        $contact->message = $requestData['message'];
        $contact->save();

        return redirect()->route('main');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/about/index.blade.php
<?php

resources/views/admin/feedback/index.blade.php
@extends('layouts.master')

@section('title', 'Список сообщений')

@section('content')
    @if($contacts->isNotEmpty())
        <div class="col-md-8">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">email</th>
                    <th scope="col">сообщение</th>
                    <th scope="col">Дата получения</th>
                </tr>
                </thead>
                <tbody>
                @foreach($contacts as $contact)
                    <tr>
                        <th scope="row">{{ $contact->id }}</th>
                        <td>{{ $contact->email }}</td>
                        <td>{{ $contact->message }}</td>
                        <td>{{ $contact->created_at}}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    @endif
@endsection()

resources/views/articles/create.blade.php
@extends('layouts.master')

@section('title', 'Создание статьи')

@section('content')
    <h3 class="pb-3 mb-4 font-italic border-bottom">
        Создание статьи
    </h3>

    @if($errors->any())
        @foreach($errors->all() as $error)
            <div class="alert alert-danger" role="alert">
                {{ $error }}
            </div>
        @endforeach
    @endif

    <form class="col-md-8" action="{{ route("articles.store") }}" method="post">
        @csrf
        @include('articles.formFields')
        <button type="submit" class="btn btn-primary">Создать</button>
    </form>
@endsection

resources/views/articles/detail.blade.php
@extends('layouts.master')

@section('title', $article->name)

@section('content')
    <div class="col-md-8">
        <div class="blog-post">
            <h2 class="blog-post-title">{{ $article->name }}</h2>
            <p class="blog-post-meta">{{ $article->created_at->format('F j, Y') }}</p>
            <p>{{ $article->detailText }}</p>
        </div>

        @articleOwner($article)
            <div style="display: flex">
                <a href="{{ route('articles.edit', ['article' => $article]) }}" class="btn btn-primary" style="margin-right: 10px"> Изменить </a>

                <form action="{{ route('articles.destroy', ['article' => $article]) }}" method="POST">
                    @method('DELETE')
                    @csrf
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </form>
            </div>
        @endarticleOwner

        <a href="/" class="btn btn-link">К списку статей</a>
    </div>
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.master')

@section('title', 'Изменить статью')

@section('content')
    <h3 class="pb-3 mb-4 font-italic border-bottom">
        Изменить статью
    </h3>

    @if($errors->any())
        @foreach($errors->all() as $error)
            <div class="alert alert-danger" role="alert">
                {{ $error }}
            </div>
        @endforeach
    @endif

    <form class="col-md-8" action="{{ route("articles.update", ['article' => $article]) }}" method="post">
        @csrf
        @method('PATCH')
        @include('articles.formFields')
        <button type="submit" class="btn btn-primary">Обновить</button>
    </form>
@endsection

resources/views/articles/formFields.blade.php
<div class="mb-3">
    <label for="slug" class="form-label">Символьный код</label>
    <input type="text" class="form-control" id="slug" name="slug" value="{{ old('slug', $article->slug) }}">
</div>
<div class="mb-3">
    <label for="name" class="form-label">Название</label>
    <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $article->name) }}">
</div>
<div class="mb-3">
    <label for="previewText" class="form-label">Краткое описание</label>
    <input type="text" name="previewText" class="form-control" id="previewText"
           value="{{ old('previewText', $article->previewText) }}">
</div>
<div class="mb-3">
    <label for="detailText" class="form-label">Полное описание</label>
    <input type="text" name="detailText" class="form-control" id="detailText" value="{{ old('detailText', $article->detailText) }}">
</div>
<div class="mb-3">
    <label for="tags" class="form-label">Теги</label>
    <input type="text" name="tags" class="form-control" id="tags" value="{{ old('tags', $article->tags->pluck('name')->implode(', ')) }}">
</div>
<div class="mb-3 form-check">
    <label class="form-check-label"  for="published">Опубликовано</label>
    <input type="checkbox" class="form-check-input" name="published" id="published" value="{{ old('published', $article->published) }}">
</div>

resources/views/contacts/index.blade.php
@extends('layouts.master')

@section('title', 'Обратная связь')

@section('content')
    <h3 class="pb-3 mb-4 font-italic border-bottom">
        Обратная связь
    </h3>

    @if($errors->any())
        @foreach($errors->all() as $error)
            <div class="alert alert-danger" role="alert">
                {{ $error }}
            </div>
        @endforeach
    @endif

    <form class="col-md-8" action="{{ route("contacts.store") }}" method="post">
        @csrf
        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="text" class="form-control" id="email" name="email" value="{{ old('email') }}">
        </div>
        <div class="mb-3">
            <label for="message" class="form-label">Сообщение</label>
            <input type="text" class="form-control" id="message" name="message" value="{{ old('message') }}">
        </div>
        <button type="submit" class="btn btn-primary">Создать</button>
    </form>
@endsection

resources/views/index.blade.php
@extends('layouts.master')

@section('title', 'Главная страница')

@section('content')
    <div class="col-md-8 blog-main">
        <h3 class="pb-3 mb-4 font-italic border-bottom">
            Список задач
        </h3>

        @if($articles->isNotEmpty())
            @foreach($articles as $article)
                <div class="blog-post">
                    <a href="{{ route("articles.detail", ["article" => $article]) }}">
                        <h2 class="blog-post-title">{{ $article->name }}</h2>
                    </a>

                    @if ($article->tags->isNotEmpty())
                        <div>
                            @foreach($article->tags as $tag)
                                <span class="badge bg-primary">{{ $tag->name }}</span>
                            @endforeach
                        </div>
                    @endif

                    @if($article->user)
                        <p class="blog-post-meta">Владелец: {{ $article->user->name }}</p>
                    @endif

                    <p class="blog-post-meta">{{ $article->created_at->format('F j, Y') }}</p>
                    <p>{{ $article->previewText }}</p>
                </div>

                <hr>
            @endforeach
        @else
            <div class="bg-danger">
                <h2>Статей нет</h2>
            </div>
        @endif
    </div>
@endsection

resources/views/layouts/footer.blade.php
<footer class="blog-footer">
    <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

resources/views/layouts/header.blade.php
<div class="container">
    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                <a class="text-muted" href="#">Subscribe</a>
            </div>
            <div class="col-4 text-center">
                <a class="blog-header-logo text-dark" href="#">Laravel Skillbox</a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <a class="text-muted" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="mx-3">
                        <circle cx="10.5" cy="10.5" r="7.5"></circle>
                        <line x1="21" y1="21" x2="15.8" y2="15.8"></line>
                    </svg>
                </a>
                @guest
                    <a class="btn btn-sm btn-outline-secondary" href="{{ route('login') }}">Sign up</a>
                    <a class="btn btn-sm btn-outline-secondary" href="{{ route('register') }}">Register</a>
                @else
                    <a class="btn btn-sm btn-outline-secondary" href="#">{{ \Illuminate\Support\Facades\Auth::user()->name }}</a>
                    <a class="btn btn-sm btn-outline-secondary" href="#" onclick="event.preventDefault(); document.getElementById('form-logout').submit();">Logout</a>
                    <form id="form-logout" action="{{ route('logout') }}" method="post" style="display:none;">
                        @csrf
                    </form>
                @endguest
            </div>
        </div>
    </header>

    <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
            <a class="p-2 text-muted" href="{{ route('main')  }}">Главная</a>
            <a class="p-2 text-muted" href="{{ route('main') }}">О нас</a>
            <a class="p-2 text-muted" href="{{ route('contacts.form') }}">Контакты</a>
            <a class="p-2 text-muted" href="{{ route('articles.create') }}">Создать статью</a>
            <a class="p-2 text-muted" href="{{ route('admin') }}">Админ.раздел</a>
        </nav>
    </div>
</div>

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="apple-touch-icon" href="https://getbootstrap.com//docs/5.1/assets/img/favicons/apple-touch-icon.png"
          sizes="180x180">
    <link rel="icon" href="https://getbootstrap.com//docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32"
          type="image/png">
    <link rel="icon" href="https://getbootstrap.com//docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16"
          type="image/png">
    <link rel="manifest" href="https://getbootstrap.com//docs/5.1/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="https://getbootstrap.com//docs/5.1/assets/img/favicons/safari-pinned-tab.svg"
          color="#7952b3">
    <link rel="icon" href="https://getbootstrap.com//docs/5.1/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/blog/">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.1/examples/blog/blog.css" rel="stylesheet">

    <title>@yield('title')</title>
</head>
<body>
@include('layouts.header')
<main role="main" class="container">
    <div class="row">
        @yield('content')

        @section('sidebar')
            <aside class="col-md-4 blog-sidebar">
                @include('tags.cloud')
            </aside>
        @show
    </div>
</main>
@include('layouts.footer')
</body>
</html>

resources/views/tags/cloud.blade.php
<div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">Теги</h4>
    <ul class="list-group">
        @foreach($tags as $tag)
            <a href="{{ route('articles.showByTag', ['tag' => $tag->id]) }}">
                <li class="list-group-item">
                    <span class="tag tag-default tag-pill pull-xs-right">{{ $tag->articles->count() }}</span>
                    {{ $tag->name }}
                </li>
            </a>
        @endforeach
    </ul>
</div>